### ISSUE TITLE
BentoBox (BSkyBlock) support

### ISSUE THREAD

**Issue by NotMyFault** [shmkane/SellStick#58]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to see support for BentoBox (BSkyBlock). I think that'd enhance the plugin a lot.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by shmkane** [comment]
What's the issue when you try to use it with BSkyBlock right now

**Comment by shmkane** [comment]
Not sure if you’re the one who asked on discord, but this issue is resolved. Here’s the discovery:

So i found it out, it doesnt work with players with OP/Pex * not sure if that was written somewhere  and  I missed it, but either way not too important I personally am not able to use them. But would be a nice feature
